#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		24
bspc config top_monocle_padding  0


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Colors
bspc config active_border_color \#d4be98
bspc config focused_border_color \#d4be98
bspc config normal_border_color \#363836

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Pavucontrol state=floating rectangle=1000x750+450+70
bspc rule -a firefox desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
